name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found!"
            exit 1
          fi

      - name: Build Docker Image
        run: |
          docker build -t my-app .
          docker tag my-app ajayrichard/my-app:latest
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push ajayrichard/my-app:latest
